Spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: Journaldb
      auto-index-creation: true
server:
  port: 8002
  servlet:
    context-path: /journel

weather_api_key: 4dcce3ec83267757ebd020e2330918b11
elevenLab_api_key: sk_89ac6c44b9c4f25929b36992eadef0518afb1aa205607969s



